# Generated by Django 4.1.7 on 2023-02-16 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='نام')),
                ('name_field', models.CharField(max_length=100, verbose_name='رشته')),
                ('discription', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='Teacher', verbose_name='عکس')),
                ('is_teacher', models.CharField(choices=[('on', 'فعال'), ('off', 'غیر فعال')], max_length=3, verbose_name='ایا معلم هست؟')),
                ('data_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
