# Generated by Django 4.1.7 on 2023-02-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='is_teacher',
            field=models.BooleanField(verbose_name='ایا معلم هست؟'),
        ),
    ]
