# Generated by Django 4.1.7 on 2023-02-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_alter_teacher_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'مدرس', 'verbose_name_plural': 'معلم ها'},
        ),
    ]
