# Generated by Django 4.1.7 on 2023-03-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_alter_teacher_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='entrance',
            field=models.CharField(default=1, max_length=20, verbose_name='رتبه کنکور'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='teaching',
            field=models.CharField(default=1, max_length=50, verbose_name=' چندسال سابقه تحصیلی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='view_resume',
            field=models.FileField(default=1, upload_to='CV', verbose_name='ارسال رزومه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Foundation',
            field=models.CharField(max_length=15, verbose_name='پایه'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='discription',
            field=models.TextField(verbose_name='توضیحات کوتاه'),
        ),
    ]
