# Generated by Django 4.2 on 2023-04-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_alter_teacher_view_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='entrance',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رتبه کنکور'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name_field',
            field=models.CharField(max_length=100, verbose_name='رشته تدریس'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teaching',
            field=models.CharField(max_length=50, verbose_name=' چندسال سابقه تدریس'),
        ),
    ]
