# Generated by Django 4.2 on 2023-04-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0015_alter_teacher_entrance_alter_teacher_name_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='section',
            field=models.CharField(default=16, max_length=50, verbose_name='مقطع'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='university',
            field=models.CharField(default=17, max_length=50, verbose_name='دانشگاه'),
            preserve_default=False,
        ),
    ]
