# Generated by Django 4.2 on 2023-04-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0016_teacher_section_teacher_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='university',
            field=models.CharField(max_length=50, verbose_name='دانشگاه محل تحصیل'),
        ),
    ]
