# Generated by Django 4.2 on 2023-04-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0017_alter_teacher_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='section',
        ),
        migrations.AddField(
            model_name='teacher',
            name='evidence',
            field=models.CharField(default=1, max_length=50, verbose_name='مدرک'),
            preserve_default=False,
        ),
    ]
