# Generated by Django 4.1.6 on 2023-02-11 17:35

import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_user_image"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", account.models.UserManager()),
            ],
        ),
    ]
