# Generated by Django 4.2 on 2023-04-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ('-user',), 'verbose_name': 'لایک', 'verbose_name_plural': 'لایک ها'},
        ),
    ]
