# Generated by Django 4.1.7 on 2023-02-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support',
            options={'verbose_name': 'پشتبانی', 'verbose_name_plural': 'پشتبانی'},
        ),
    ]
